{
  "status" : 200,
  "data" : {
    "app_thumbnail_url" : "https://img.littlefox.co.kr/static/contents/display/DP000357/image_thum_app_en.png?1700686799",
    "title_url" : "https://img.littlefox.co.kr/static/contents/display/DP000357/image_title_en.png?1700686799",
    "series" : {
      "id" : "FS0088",
      "level" : 1,
      "is_single" : "Y"
    },
    "id" : "DP000357",
    "web_thumbnail_url" : "https://img.littlefox.co.kr/static/contents/display/DP000357/image_thum_en.png?1700686799",
    "contents" : [
      {
        "service_info" : {
          "service" : "F",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "F",
          "quiz" : "F",
          "translate" : "N",
          "story" : "F",
          "crossword" : "N",
          "original_text" : "F",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000580/notext_ipad.jpg?1674029206",
        "id" : "C0000580",
        "open_date" : "2022-02-10",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Teddy's Day"
      },
      {
        "service_info" : {
          "service" : "F",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "F",
          "quiz" : "F",
          "translate" : "N",
          "story" : "F",
          "crossword" : "N",
          "original_text" : "F",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000586/notext_ipad.jpg?1674029574",
        "id" : "C0000586",
        "open_date" : "2021-12-16",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Dreams"
      },
      {
        "service_info" : {
          "service" : "F",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "F",
          "quiz" : "F",
          "translate" : "N",
          "story" : "F",
          "crossword" : "N",
          "original_text" : "F",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000943/notext_ipad.jpg?1625526351",
        "id" : "C0000943",
        "open_date" : "2021-04-26",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "I Like Ice Cream"
      },
      {
        "service_info" : {
          "service" : "F",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "F",
          "quiz" : "F",
          "translate" : "N",
          "story" : "F",
          "crossword" : "N",
          "original_text" : "F",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000537/notext_ipad.jpg?1611877164",
        "id" : "C0000537",
        "open_date" : "2021-01-29",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "I See"
      },
      {
        "service_info" : {
          "service" : "F",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "F",
          "quiz" : "F",
          "translate" : "N",
          "story" : "F",
          "crossword" : "N",
          "original_text" : "F",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0006767/notext_ipad.jpg?1609396525",
        "id" : "C0006767",
        "open_date" : "2016-02-25",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "This Is My Body"
      },
      {
        "service_info" : {
          "service" : "F",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "F",
          "quiz" : "F",
          "translate" : "N",
          "story" : "F",
          "crossword" : "N",
          "original_text" : "F",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0003481/notext_ipad.jpg?1609392274",
        "id" : "C0003481",
        "open_date" : "2010-03-09",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Float or Sink"
      },
      {
        "service_info" : {
          "service" : "F",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "F",
          "quiz" : "F",
          "translate" : "N",
          "story" : "F",
          "crossword" : "N",
          "original_text" : "F",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000557/notext_ipad.jpg?1609402065",
        "id" : "C0000557",
        "open_date" : "2002-12-03",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Merry Christmas!"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000625/notext_ipad.jpg?1647905107",
        "id" : "C0000625",
        "open_date" : "2022-03-24",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Things I See"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000569/notext_ipad.jpg?1649291215",
        "id" : "C0000569",
        "open_date" : "2022-03-17",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Rainbow Car"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000736/notext_ipad.jpg?1646698287",
        "id" : "C0000736",
        "open_date" : "2022-03-10",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Dressing Up"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000715/notext_ipad.jpg?1646175966",
        "id" : "C0000715",
        "open_date" : "2022-03-03",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Seasons Are Fun"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000849/notext_ipad.jpg?1645506181",
        "id" : "C0000849",
        "open_date" : "2022-02-24",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "New Home"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0003460/notext_ipad.jpg?1644880994",
        "id" : "C0003460",
        "open_date" : "2022-02-17",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "It's Snowy!"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000687/notext_ipad.jpg?1643334601",
        "id" : "C0000687",
        "open_date" : "2022-02-03",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "What Is Missing?"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000620/notext_ipad.jpg?1643073495",
        "id" : "C0000620",
        "open_date" : "2022-01-27",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Mr. Shapey"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000840/notext_ipad.jpg?1642484226",
        "id" : "C0000840",
        "open_date" : "2022-01-20",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "What Do You See?"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000592/notext_ipad.jpg?1641856714",
        "id" : "C0000592",
        "open_date" : "2022-01-13",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Big and Small"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000893/notext_ipad.jpg?1641257213",
        "id" : "C0000893",
        "open_date" : "2022-01-06",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Costume Party"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000855/notext_ipad.jpg?1640734507",
        "id" : "C0000855",
        "open_date" : "2021-12-30",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Surprise, Teacher!"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000731/notext_ipad.jpg?1640060443",
        "id" : "C0000731",
        "open_date" : "2021-12-23",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "At School"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0001052/notext_ipad.jpg?1619998631",
        "id" : "C0001052",
        "open_date" : "2021-05-03",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Me Too!"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000560/notext_ipad.jpg?1618446881",
        "id" : "C0000560",
        "open_date" : "2021-04-19",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Yummy Soup"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000804/notext_ipad.jpg?1617838229",
        "id" : "C0000804",
        "open_date" : "2021-04-12",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Sharing"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000589/notext_ipad.jpg?1647830175",
        "id" : "C0000589",
        "open_date" : "2021-02-05",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Who Is Working?"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000552/notext_ipad.jpg?1611117820",
        "id" : "C0000552",
        "open_date" : "2021-01-22",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Balloons"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000813/notext_ipad.jpg?1610520923",
        "id" : "C0000813",
        "open_date" : "2021-01-15",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Where Is Kitty?"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000548/notext_ipad.jpg?1609890017",
        "id" : "C0000548",
        "open_date" : "2021-01-08",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Greedy Monkey"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0008511/notext_ipad.jpg?1607580590",
        "id" : "C0008511",
        "open_date" : "2020-12-16",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "The Blobs in the House of Mirrors"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0008510/notext_ipad.jpg?1607393575",
        "id" : "C0008510",
        "open_date" : "2020-12-09",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "The Blobs on the Merry-Go-Round"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0008509/notext_ipad.jpg?1585705421",
        "id" : "C0008509",
        "open_date" : "2020-04-03",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "The Blobs and the Bumper Car"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0008508/notext_ipad.jpg?1585197054",
        "id" : "C0008508",
        "open_date" : "2020-03-27",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "The Blobs at the Gift Shop"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0006768/notext_ipad.jpg?1609398976",
        "id" : "C0006768",
        "open_date" : "2016-02-18",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Our Faces"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0003487/notext_ipad.jpg?1609399967",
        "id" : "C0003487",
        "open_date" : "2010-08-03",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Sad, Sadder, Saddest"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0003485/notext_ipad.jpg?1609400338",
        "id" : "C0003485",
        "open_date" : "2010-06-08",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Snowball"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0003486/notext_ipad.jpg?1609391970",
        "id" : "C0003486",
        "open_date" : "2010-06-01",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Don't Be Sad! Be Happy!"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0003498/notext_ipad.jpg?1609400703",
        "id" : "C0003498",
        "open_date" : "2010-05-04",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Splat!"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0003482/notext_ipad.jpg?1609392422",
        "id" : "C0003482",
        "open_date" : "2010-04-06",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Freddy, Fanny, and Felix"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0003464/notext_ipad.jpg?1609399756",
        "id" : "C0003464",
        "open_date" : "2010-02-23",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Red Light, Green Light"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0003473/notext_ipad.jpg?1609397392",
        "id" : "C0003473",
        "open_date" : "2010-01-26",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "My Team"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0003467/notext_ipad.jpg?1609394637",
        "id" : "C0003467",
        "open_date" : "2009-12-14",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Look Left, Look Right"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0003465/notext_ipad.jpg?1609401737",
        "id" : "C0003465",
        "open_date" : "2009-11-09",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Who Is It?"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0003488/notext_ipad.jpg?1609391009",
        "id" : "C0003488",
        "open_date" : "2009-10-12",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "The Best"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0003480/notext_ipad.jpg?1609391757",
        "id" : "C0003480",
        "open_date" : "2009-10-05",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Dinosaurs"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0003462/notext_ipad.jpg?1609390709",
        "id" : "C0003462",
        "open_date" : "2009-09-28",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Baseball!"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0003468/notext_ipad.jpg?1638401482",
        "id" : "C0003468",
        "open_date" : "2009-08-31",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "My Day"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0003483/notext_ipad.jpg?1609390414",
        "id" : "C0003483",
        "open_date" : "2009-08-24",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "At the Zoo"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0003463/notext_ipad.jpg?1609397808",
        "id" : "C0003463",
        "open_date" : "2009-08-17",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "One Cloud, Many Clouds"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0003471/notext_ipad.jpg?1609397178",
        "id" : "C0003471",
        "open_date" : "2009-08-10",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "My Piggy Bank"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0003461/notext_ipad.jpg?1609398440",
        "id" : "C0003461",
        "open_date" : "2009-08-03",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "On the Hill"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0003458/notext_ipad.jpg?1609391596",
        "id" : "C0003458",
        "open_date" : "2009-07-27",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Cute!"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0003313/notext_ipad.jpg?1609395736",
        "id" : "C0003313",
        "open_date" : "2009-04-09",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Musical Chairs"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0001381/notext_ipad.jpg?1609389937",
        "id" : "C0001381",
        "open_date" : "2005-12-26",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "The Ant"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0001354/notext_ipad.jpg?1609394484",
        "id" : "C0001354",
        "open_date" : "2005-11-15",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Lift and Look with Maxie"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0001117/notext_ipad.jpg?1609400192",
        "id" : "C0001117",
        "open_date" : "2005-01-14",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Sledding"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0001030/notext_ipad.jpg?1609399275",
        "id" : "C0001030",
        "open_date" : "2004-10-28",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Pick Up a Leaf"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000969/notext_ipad.jpg?1609390259",
        "id" : "C0000969",
        "open_date" : "2004-08-12",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "At the Beach"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000760/notext_ipad.jpg?1663552134",
        "id" : "C0000760",
        "open_date" : "2004-07-01",
        "sub_name" : "",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "On a Rainy Day"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000881/notext_ipad.jpg?1609400879",
        "id" : "C0000881",
        "open_date" : "2004-04-19",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Dark Cloud"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000871/notext_ipad.jpg?1609398814",
        "id" : "C0000871",
        "open_date" : "2004-04-01",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Ouch!"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000828/notext_ipad.jpg?1609399465",
        "id" : "C0000828",
        "open_date" : "2004-02-02",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Pop the Popcorn!"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000821/notext_ipad.jpg?1609398666",
        "id" : "C0000821",
        "open_date" : "2004-01-15",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "On the Stage"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000793/notext_ipad.jpg?1609401463",
        "id" : "C0000793",
        "open_date" : "2003-11-27",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "We Smile"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000745/notext_ipad.jpg?1659939405",
        "id" : "C0000745",
        "open_date" : "2003-09-16",
        "sub_name" : "",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "I Can Walk"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000691/notext_ipad.jpg?1609393315",
        "id" : "C0000691",
        "open_date" : "2003-07-14",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Dig a Little Hole"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000642/notext_ipad.jpg?1645486965",
        "id" : "C0000642",
        "open_date" : "2003-05-07",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Go, Go, Go!"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000633/notext_ipad.jpg?1609392814",
        "id" : "C0000633",
        "open_date" : "2003-04-17",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Grandpa's Farm"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000617/notext_ipad.jpg?1609390837",
        "id" : "C0000617",
        "open_date" : "2003-03-20",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Spring Is Here"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000609/notext_ipad.jpg?1665014691",
        "id" : "C0000609",
        "open_date" : "2003-03-06",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Pass the Pie Please"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000571/notext_ipad.jpg?1609400465",
        "id" : "C0000571",
        "open_date" : "2002-12-31",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Snowman"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000568/notext_ipad.jpg?1609391183",
        "id" : "C0000568",
        "open_date" : "2002-12-24",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Christmas Is Coming"
      },
      {
        "service_info" : {
          "service" : "Y",
          "vocabulary" : "N",
          "flash_card" : "N",
          "sentence" : "N",
          "ebook" : "Y",
          "quiz" : "Y",
          "translate" : "N",
          "story" : "Y",
          "crossword" : "N",
          "original_text" : "Y",
          "starwords" : "N"
        },
        "thumbnail_url" : "https://img.littlefox.co.kr/static/contents/img/C0000545/notext_ipad.jpg?1609393063",
        "id" : "C0000545",
        "open_date" : "2002-11-12",
        "level" : 1,
        "user_service_info" : {
          "flash_card" : "N",
          "vocabulary" : "N",
          "ebook" : "N",
          "sentence" : "N",
          "quiz" : "N",
          "translate" : "N",
          "story" : "N",
          "crossword" : "N",
          "original_text" : "N",
          "starwords" : "N"
        },
        "type" : "S",
        "name" : "Happy Birthday"
      }
    ],
    "name" : "Single Stories"
  }
}
